### ISSUE TITLE
sublime-rbx-lsp won't start 

### ISSUE THREAD

**Issue by user7500** [Nexure/sublime-rbx-lsp#1]
Whenever I open a .lua file in Sublime Text, this error appears: 
![image](https://user-images.githubusercontent.com/71734690/156852031-d904a385-143d-4e6f-8472-fa284fe288b2.png)
It started to occur once a cleared my drive to free up space. I've tried removing the repo from package control and removing it.

**Comment by user7500** [comment]
Reinstalling Sublime Text and the extension didn't help either

**Comment by user7500** [comment]
Spoke with Nightrains a while ago, and he helped to resolve the issue.

**Comment by zaiisao** [comment]
Please... when you resolved the issue, explain what the problem was and how it was resolved. Otherwise, people with the same issue will be left in the dark.
